blocklyc.html, fileManager.js, help.html, index.html, new-project.html, page_footer.html, recent-projects.html
This PR contains the starter set of HTML and JavaScript files required for the solo version of BlocklyProp.
=> Add project source files

page_footer.html
Replace the placeholder version information (v999) with the current release details.
=> Set release to 1.3.461.

blocklyc.html, index.html, page_footer.html
Removes bootstrap for blockylc.html and index.html
supports HTML refactor
Updates jQuery
Updates ACE editor
Adds jQuery modal (plugin)
Adds Filesaver.js (removes inline functions)
Removes inline styles and scripts from HTML pages (except for client app instruction modals targeted for later revision/refactor).
=> Cdn 155 update j query remove bootstrap

page_footer.html
Last step before launching beta version of Solo into AWS.
=> Bump version to v1.3.456.

new-project.html
A minor nit that the linter was complaining about.
=> Correct minor error in link tag.

blocklyc.html, page_footer.html
Increment build number to 1.2.471 for another beta release.
=> Update for Beta #2 v1.3.471

blocklyc.html, page_footer.html
Resolve save project before new project modal appears.
Remove BlocklyProp system user authentication elements.
Update HTML comments.
=> Beta 3 v.1.3.473

blocklyc.html, page_footer.html
=> Update to sync with CDN PR #213

src/deprecated/latest.js, src/deprecated/shared-editor-demo.js, src/deprecated/shared-editor.js
Adding shared editor js files and latest.js. All are not referenced in the Solo project.
=> Move unused files to the deprecated folder.

blocklyc.html, src/editor.js
Addresses issue #90.
This update removes the references to user_authentication, related code and the user_auth html meta tag.
=> Remove user authentication code in editor.js

index.html
Release 1.3.489.
Addressed issue #92.
=> Bump version to 1.3.489.

.gitignore, blocklyc.html, src/blockly/generators/propc/variables.js, src/blocklyc.js, src/blocklypropclient.js, src/editor.js, src/propterm.js
PR 108 is breaking array block variables. Rolling back that change until the issue is completely resolved.
=> Revert PR 108

src/blockly/generators/field_code.js, src/blockly/generators/propc/base.js, src/blockly/generators/propc/variables.js
Minimum fixes required to address all console warnings and errors sourced by block definitions when uploading demo project ID 2075 into solo.
=> Comment, custom code, and constant value block bug fixes

blocklyc.html, index.html, src/blocklypropclient.js, src/editor.js, src/modals.js, src/project.js
This update implements a Project class that will eventually replace the functionality of the global projectData variable and related code. 
Other changes:
* Correct issue where com port dropdown enumeration failed.
* Remove more inline code that was only relevant to the BlocklyProp project.
=> Create project class feature

.eslintrc.yml, src/editor.js, src/modals.js
Update redefined constants that were missed in PR #143
Add more discovered globals to eslint config.
Deprecate global idProject because Solo is not using it.
Correct issue where local variable pd was undeclared.
=> PR 143 corrections

blocklyc.html, index.html
Addresses an element of issue #106 to correct toolbar button styling.
Bumping version to 1.3.503.
=> Correct toolbar buttons

index.html
We left out the change for the version bump when .504 was released to address issue #159
=> Increment version for release to fix #159.

src/blockly/generators/propc/gpio.js
=> Fix SD card blocks

src/editor.js
Addresses issue parallaxinc/blocklyprop-cdn#227
Create a stub function to satisfy the #term-graph-setup onClick event callback. This stub will be fleshed out at a later date as needed.
=> (cdn-227) Create a stub function that will be updated as needed.

blocklyc.html, index.html
Addresses issue #96 and adds banners to both HTML pages with a message suggesting to the user that they enable Javascript for the best experience.
=> (solo-96) Add noscript tags and minimal styling.

src/blockly/language/en/_messages.js
My IDE picked up a few spelling errors in the messages file. This patch corrects those words.
=> Correct spelling errors in the messages file.

src/propterm.js
Begins to address #81 
Begins the process of refactoring the terminal into its own class.
This PR is variable name cleanup and dead code removal.
To test
- build a program that echos a users input to the terminal.
- ![image](https://user-images.githubusercontent.com/19737272/69754583-1736c800-110b-11ea-97ea-ae15f98a9b63.png)
- Type into a verify that the terminal is repeating what was sent.
Verify with both BP-Client and BP-Launcher (each use different mechanisms int he code).
This should be a sufficient test procedure for all #81 related PRs.
=> WIP: Solo 81a Variable name cleanup, small refactors to remove dead code

src/utils.js
Fixes an error I introduced when I went through the last set of merge conflicts.
=> Fix property definition test

index.html, src/index.js
Just noticed this one in the splash page...
=> Fix instance of getURLparameter

index.html, src/editor.js, src/globals.js, src/index.js
Bump release version to 1.3.511
This completes the rebranding of the Test Solo site.
Move string constants to the globals.js file.
Including the globals.js in the index.html page.
=> Add code to display correct branding in the Test environment.

src/modals.js
Refactor dialog to confirm abandon current project.
Remove unreferenced, deprecated functions.
=> Remove Save download dialog box

src/blockly/generators/propc/communicate.js, src/blockly/generators/propc/gpio.js, src/blockly/generators/propc/heb.js, src/blockly/generators/propc/sensors.js, src/blocklyc.js, src/blocklypropclient.js, src/editor.js, src/globals.js, src/modals.js
The global projectData is an object, not an array. The code base was accessing elements of the object with a combination of object.element and object['element'] constructs. Refactor code that references projectData to treat it as an object, using the object.element construct.
This will ease the transition to using the Project class throughout the project.
=> Refactor inconsistant projectData references

src/editor.js, src/globals.js
Correct error in initializing the global projectData object.
Correct test for valid projectData. Length is not a valid attribute for an object.
=> Updates to projectData global handling

index.html
Preparing to push release candidate 1 to SoloCup.
=> Bump version for v.1.4.0 RC-1 push to SoloCup.

index.html
Ready to deploy another release candidate.
=> Bump version to 1.4.0-rc2.

src/blockly/generators/propc/communicate.js
Begin adding inline documentation to the communication.js
=> Add javascript docs to methods

src/editor.js
Remove unneeded comments from previous change.
=> Clean up comments.

src/editor.js
WIP #261 
Refactor project metadata parsing into separate functions to simplify the core code that loads a project from storage.
=> Add code to identify individual project blocks.

src/blockly/generators/propc/sensors.js, src/blockly/language/en/messages.js
Addresses #265
A simplified set of blocks for the LIS3DH sensor - these blocks DO NOT support using multiple sensors in the same project.
To test:
Create a programs using each combination of init, read, and temperature blocks.
Save and reopen projects using LIS3DH blocks.
Make sure field values are retained when blocks are reopened.
Make sure blocks generate working/usable C code.
=> Solo 265-B simpler LIS3DH blocks

index.html
Update application version to 1.4.1.1 for release of updated LIS3DH blocks.
=> Bump to patch level 1.

src/editor.js
Begin integrating the Project class into mainline code. This update simply populates a Project class object with the same data as used in the projectData object, then compares them to ensure that all of the key value pairs map correctly.
=> Enable code to create Project object in parallel with existing path.

blocklyc.html, src/blocklyc.js, src/blocklypropclient.js, src/style-editor.css
First resubmission of code done against #200, begins to address #279.
Removes unnecessary UI, simplifies functions that toggle UI, renames one function.
=> Solo 279 A - Simplify/refactor UI elements for client connection

src/blockly/generators/propc/sensors.js
Addresses issue discovered in testing for #265 
Fixes capitalization error in code generated.
=> Solo 265 C - Fix ADC function name

src/blockly/generators/propc/sensors.js, src/editor.js
Add updates that do not break project loading to return us back to the develop branch.
=> Updates to last known working

src/blockly/language/en/messages.js, src/blocklyc.js, src/blocklypropclient.js
Adds/improves messages related to the console/device connection in the UI.
=> Solo 279-B Add connection messages

index.html
Update version number in the index.html file.
=> Pushing out Solo 1.4.1 beta 3

index.html
Update the version on the home page to v1.4.1
=> Release 1.4.1

index.html
Corrects text on the ADC setting of the LIS3DH block init.
That's all it does.
=> Release 1.4.2.2

src/blockly/language/en/messages.js
Addresses issue #305.
Update BP client update message to make it more of a recommendation or suggestion.
=> Update BlocklyProp Client Update message

index.html, src/editor.js
Bump version to 1.4.2.2 RC-2
Minor formatting applied to editor.js.
=> Release Candidate 2 - v1.4.2.3

src/blockly/generators/propc/sensors.js
Addresses issue #311
This update replaces the single 'set zero' adjustment with two settings; one to adjust the ground offset and another to adjust the 3.3V offset. The two settings inform a ramping function in the library that now provides a more accurate reading throughout the measured range.
=> Replace single ADC setting with high and low settings.

src/blockly/generators/propc/gpio.js
Addresses issue #313 
Changed freq out block orientation from horizontal to vertical
=> Solo #313 - Reorient Frequency Out block

src/blocklyc.js, src/blocklypropclient.js
Simply a find-replace for a number of variable and function names.  In a few cases, global variables were replaced with variables from within the `clientService` object to reduce the total number of globals used overall.
=> Solo 200 resubmit F update variable and function names

.gitignore, package-lock.json, package.json, webpack.config.js
This is targeted at the process of building bundles for Blockly and Solo internal packages.
=> Adding basic webpack configuration (WIP)

.eslintrc.yml, index.html, package-lock.json, package.json, src/globals.js, src/index.js
Implement first stage of webpack deployment. 
* Updated configuration files to support ES6 modules and to assign a entry script for each of the html pages used in the project.
* Refactor the globals.js to create exports to be consumed in other modules.
* Refactor the index.html and index.js files to support modules.
=> WIP - Implement home page with modules

index.html
Update version number for release 1.4.2 to staging.
=> Release 1.4.2

src/blockly/generators/propc/gpio.js
Reversing the block configuration change called for in #313
These are not the droids you are looking for.
=> Revert Solo #313

blocklyc.html, package-lock.json, package.json, src/blockly/generators/propc.js, src/blocklyc.js, src/blocklypropclient.js, src/editor.js, src/globals.js, src/modals.js, src/propterm.js, src/utils.js, webpack.config.js
Add exports to adjacent files.
Add auto-rebuild to the webpack configuration.
=> WIP - Refactor editor.js to use modules.

.eslintrc.yml, blocklyc.html, index.html, package-lock.json, package.json, src/blockly/generators/propc.js, src/blockly/generators/propcToolbox.js, src/blockly/language/en/messages.js, src/blocklyc.js, src/blocklypropclient.js, src/editor.js, src/globals.js, src/modals.js, src/project.js, src/utils.js, webpack.config.js
ES6 modules do not permit modifiable global variables. Everything that is in the global space needs to be refactored into corresponding modules.
=> Patch feature webpack update

src/editor.js, src/project.js
Add board type conversion method to translate a board type string to a ProjectBoardType object.
Corrected errors in the Project A+B comparison method.
Cleaned up logic issue in the constructor that were discovered during testing.
=> Update Project class

src/blocklyc.js, src/blocklypropclient.js
Removes the `term` and `newTerminal` globals and replaces them with a variable inside of the clientService object.
=> Remove term and newTerminal globals

index.html
Release interim update to correct several issues reported since the 1.4.2 release.
=> Roll out a bug fix. Update version to 1.4.2a

index.html, src/project.js
Found an error in the Project class constructor. Comparing a string to an object does not work so well.
=> Patch develop 1.4.2b

index.html, src/blockly/generators/propc/gpio.js, src/project.js
Addressed Project constructor error.
=> Release 1.4.2b

index.html, src/project.js
One more Project initialization error. All board types tested, so this one should stick.
=> Solo 1.4.2c

index.html, src/project.js
Maybe the last push to fix Project code.
=> Release 1.4.2c

index.html, src/blocklyc.js, src/editor.js, src/modals.js, src/project.js, src/propterm.js
This update encloses the code that interacts with the Project class within try/catch blocks to trap errors before they impact the user experience. 
Enclosed the code within the checkForComPorts function in a try/catch block to isolate a ReferenceError detected in this function. The code was unable to find the clientService or the clientService.type. The report is not that specific.
=> Update to address Project errors

src/editor.js, src/project.js
Trying to keep up with the develop branch.
=> Patch feature webpack 03 06

package-lock.json, package.json, webpack.config.js
Add webpack plugins for css and styles.
=> Webpack plugin update

src/blockly/generators/propc.js, src/blockly/generators/propc/communicate.js, src/blockly/generators/propc/gpio.js, src/blockly/generators/propc/s3.js, src/blocklyc.js, src/globals.js, src/modals.js, src/modules/constants.js, src/modules/editor.js, src/modules/project_file_validation.js, src/style-editor.css
Adding in code from PR #370 to keep the branches in sync.
=> Patch from develop

blocklyc.html, package-lock.json, package.json, src/globals.js, src/modals.js, src/modules/editor.js, src/modules/project.js, src/modules/project_save_timer.js
More updates to editor.js to clean up all the details it manages.
Corrected an issue where the wrong workspace was being passed into Blockly core.
=> Module conversion update

src/propgraph.js, tests/graphtest.html
This is the start for work to create a javascript class for the graphing functionality in BlocklyProp.
It includes, to start, a separate file for the new graphing class (`propgraph.js`), and a HTML page for testing the class (`tests/graphtest.html`).
This is a work in progress.
=> Create feature branch - graphing class

package-lock.json, package.json, src/modules/blocklyc.js, src/modules/editor.js, src/modules/modals.js, src/modules/project.js, webpack.config.js
Refactor showInfo into 2 UI components.
Correct more issues related to the projectData global that was removed.
WIP: UI now loads most blocks. Blocks that reference profile.default need to be refactored.
=> Patch fm 319

src/README.md, src/blockly/generators/propc/base.js, src/blockly/generators/propc/gpio.js, src/blockly/generators/propc/sensors.js, src/globals.js, src/modules/editor.js, src/modules/project.js, src/modules/project_profile.js
Correct offset error in project code loader. Current code was grabbing the '<' from the checksum tag. This made the XML invalid and Blockly core choked on it.
Refactor font processing into a separate method.
Added an option arg to Project constructor to set default project
Add a global projectProfile to the windows object.
Started refactoring custom blocks to use the windows.projectProfile variable.
=> Various updates

src/README.md, src/blockly/generators/propc/base.js, src/blockly/generators/propc/heb.js, src/blockly/generators/propc/s3.js, src/blockly/generators/propc/sensors.js
Refactor remaining propc blocks to replace profile.default with window.projectProfile.
Correct another misspelled 'this.disabled'.
=> Refactor remain files in ./propc folder

blocklyc.html, index.html, src/blockly/language/en/messages.js, src/blocklypropclient.js, src/editor.js, src/project.js
Temporarily addresses issue #391. 
Located a condition in findClient() that was testing the connection state before the connection was fully open. The temporary workaround applied here is to delay the remaining code in findClient() from executing until the socket is opened.
=> Hotfix 1.4.2.7

blocklyc.html, src/README.md, src/blockly/generators/propc.js, src/blockly/generators/propc/base.js, src/blockly/generators/propc/communicate.js, src/blockly/generators/propc/control.js, src/blockly/generators/propc/gpio.js, src/blockly/generators/propc/heb.js, src/blockly/generators/propc/procedures.js, src/blockly/generators/propc/sensors.js, src/blockly/generators/propc/variables.js, src/modules/blocklyc.js, src/modules/editor.js, src/modules/modals.js, src/modules/project.js, src/modules/project_save_timer.js
Refactor checkLeave() to isProjectChanged() to better represent what is really happening in the code.
Add project.compare method to evaluate any changes between to projects.
=> Patch fm 0330a

.eslintrc.yml, blocklyc.html, package-lock.json, package.json, src/blockly/language/en/messages.js, src/modules/blockly/language/en/messages.js, src/modules/blocklyc.js, src/modules/code_editor.js, src/modules/editor.js, src/modules/modals.js, src/modules/project.js, src/modules/toolbar_controller.js, src/modules/toolbox_data.js
This is still a work in progress. Resolved additional issues in the blocklyc.js module.
=> Fixes to unresolved references.

blocklyc.html, src/modules/blocklyc.js, src/modules/editor.js, src/modules/toolbar_controller.js, webpack.config.js
Refactor the compiler buttons toolbar controller to separate UI interactions from the business logic.
Add a close() method to the clientServices object to ensure that the various settings affected by a closed connection were reset to their correct states, post socket closure.
=> Patch fm 200411

blocklyc.html, src/modules/blocklyc.js, src/modules/constants.js, src/modules/editor.js, src/modules/project.js, src/modules/utility.js
Addresses #428 by moving the onClick() handler assignment to editor.js
Addresses #427 by ensuring that the project code XML is properly and consistently formatted during project load and save.
Partially addresses #425 by separating the project file loading from the population of the Project class. This will allow for the separation of file loading from the tasks of appending or replacing the existing project.
=> Patch fm 200429

package-lock.json, package.json, src/blockly/generators/propc/base.js
Update packages to deploy security updates.
Add comments to color picker code.
=> Patch 200527 develop

src/modules/blockly/generators/propc/base.js, src/modules/blockly/generators/propc/communicate.js
Partially addresses #442 
Correct code to use correct project property.
=> Clean up random block code generator.

blocklyc.html, package-lock.json, package.json, src/modules/blockly/generators/propc/communicate.js, src/modules/code_editor.js, src/modules/constants.js, src/modules/editor.js, src/modules/modals.js, src/modules/project.js, src/modules/toolbar_controller.js, src/modules/utility.js
This update corrects an issue where opening a project would install an additional callback to the project load event. Subsequent invocations of the Open Project dialog add an additional callback and process the existing callbacks, causing the project to be loaded n+1 times.
Updated the login in the toolbar controller to better handle S3 projects and eliminate the Load to EEPROM and Graphing buttons in all use cases.
=> Patch b6 wip

src/modules/dialogs/import_project.js, src/modules/dialogs/open_project.js
This PR implements the replace project component of the Project Import feature. This functionality will replace the current project with the selected project. The user is prompted to save the current project before proceeding.
=> Implement Project Import / Replace Feature

package-lock.json, package.json, src/modules/blockly/generators/propc/base.js, src/modules/blockly/generators/propc/sensors.js, src/modules/blocklyc.js, src/modules/client_connection.js, src/modules/client_service.js, src/modules/code_editor.js, src/modules/constants.js, src/modules/editor.js
WIP for issue Solo #432. The custom C coding block relies on a custom FieldAceEditor field. This custom field relies on the Google Closure-Compiler, which is not incorporated into the current build process.
=> Patch fm 200613a - WIP 

package-lock.json, package.json, src/modules/blockly/language/en/messages.js
Update the Sentry package to current release 5.19.2
=> Patch sentry upgrade

src/modules/blockly/generators/propc/procedures.js
Added a workaround for issue #497 to quiet the error until a cog block is created.
=> Release 1.5.2

package-lock.json, package.json, src/modules/blockly/generators/propc.js, src/modules/blockly/generators/propc/aliaes.js, src/modules/blockly/generators/propc/base.js, src/modules/blockly/generators/propc/communicate.js, src/modules/blockly/generators/propc/heb.js, src/modules/blockly/generators/propc/oled.js, src/modules/blockly/generators/propc/procedures.js, src/modules/blockly/generators/propc/s3.js, src/modules/blockly/generators/propc/sensors.js, src/modules/client_service.js, src/modules/constants.js, src/modules/editor.js, src/modules/toolbox_data.js
Updates to address issues #501, #503, and #504
=> Releases 1.5.3

package-lock.json, package.json, src/modules/constants.js
Update application version.
Disable and update Sentry package.
=> Patch 1.5.7 packages

src/modules/blockly/generators/propc/communicate.js
Replace compound if/else with a switch statement.
=> Refactor serial_receive_text. Add comments.

src/modules/constants.js
Set release v1.5.7
Enable Sentry.
=> Final update to Release 1.5.7

src/modules/index.js
Removes nearly all of the jQuery selectors on the home page.
=> Refactor to remove jquery selectors.

src/modules/constants.js
Bumping version for new updates for 1.5.7.2
=> Bump up release number for alpha-1.

src/modules/client_connection.js, src/modules/constants.js, src/modules/dialogs/import_project.js, src/modules/dialogs/new_project.js, src/modules/dialogs/open_project.js, src/modules/editor.js, src/modules/project.js, src/modules/project_save_timer.js
Version 1.5.7.2-a2
Remove debug messages that have been building up over the past few months.
=> Remove unneeded debugging messages.

src/modules/blockly/generators/propc/sd_card.js
Reintroduce the update that addresses issue #536.
=> Adding ampersand to allow non-character data types to be used.

src/modules/blockly/generators/propc.js, src/modules/blockly/generators/propc/sd_card.js, src/modules/blockly/language/en/messages.js, src/modules/constants.js, src/modules/toolbox_data.js
Add a separate close block to the SD Card block family.  
Updated emitted code to properly format the close sd block code.
=> Patch 1.5.7.2 a3 sd close

.gitignore, package-lock.json, src/modules/blockly/generators/propc/communicate.js, src/modules/blocklyc.js, src/modules/compiler.js, src/modules/constants.js, src/modules/editor.js, src/modules/utility.js
Correct issue where the UI was not listing the compiler error messages when the program failed to compile.
Move the prettyPrint function to the utility module.
Begin work on serial_send_text block that is not warning if a serial initialization block is either not present or is disabled.
=> Patch 1.5.8 rc2

src/modules/blocklyc.js, src/modules/compiler.js
The loader was not checking the results returned from the compiler and was emitting a "Downloading..." message when it was not going to attempt a download.
=> Do not display the 'Downloading...' message is compile failed.

src/modules/constants.js
Release 1.5.8
Disable all debugging code.
=> Release 1.5.8

package.json, webpack/prod.config.js
Clear ./dist folder before build.
This pr is a salvage operation from a failed local development branch.
=> Clean up Webpack prod config file.

package-lock.json, package.json, webpack/base.config.js, webpack/dev.config.js, webpack/prod.config.js
Update configuration and webpack plugins to prepare for webpack-5.
=> Update webpack in preparation for migrate to webpack 5

package-lock.json, package.json, src/modules/blockly/generators/propc/sd_card.js, test/mocha/block_test.js, test/mocha/index.html, test/mocha/mocha.opts, test/mocha/run_mocha_tests_in_browser.js, test/mocha/test_helpers.js, test/run_all_tests.sh
Add files for unit testing.
Correct invalid use of 'this' in an anonymous function in the SD Card block.
=> Patch solo testing

package-lock.json, package.json
Upgrade the sentry browser and sentry tracing packages to current release.
=> Issue 593 - Update sentry package

package-lock.json, package.json
Update css-loader to avoid DDOS attack vector.
=> Update css-loader to correct security vulnerability.

blocklyc.html, src/modules/blockly/language/en/messages.js, src/modules/code_editor.js, src/modules/editor.js
Begin work on issue #599.
Disabled UI relevant UI elements and event handlers.
=> Disable UI elements for deprecated XML edit

src/modules/constants.js, src/modules/index.js
The string.indexOf() method can return zero it the matching string occurs at the beginning of the target string.
[/shaking head]
=> Correct error where indexOf() 

src/modules/index.js
The image was being referenced from the source folder. It should always reference from the ./dist folder.
=> Correct pact for solocup image.

src/modules/constants.js, src/modules/editor.js, src/modules/index.js, test/run_all_tests.sh
Update the index.js script to detect all non-production environments and render SoloCup UI when not in production.
Update the test script to stop tests when lint errors are detected.
Begin testing the WebPack module pre-fetch feature.
Update build number
=> Post-WebPack 5 minor updates

src/modules/index.js
Replace jQuery statements with native JS statements.
=> Refactor more jQuery bits into native Javascript

package-lock.json
An artifact from the js-cookie package remained in the package-lock.json file
=> Remove js-cookie package

src/modules/constants.js, src/modules/dialogs/new_project.js, src/modules/dialogs/open_project.js
Missed references to a method that was using cookies.
=> Missed committing 2 modules to remove js-cookie package

src/modules/client_connection.js, src/modules/project.js, src/modules/toolbar_controller.js
Addresses issue raised in #619.
Correct additional lint warnings.
=> Patch issue 619

src/modules/constants.js, src/modules/dialogs/import_project.js, src/modules/dialogs/open_project.js
Add code to remove the temporary copy of a project that was loaded as a result of a Open Project or Import Project dialog.
=> Issue 622 patch 1

src/modules/dialogs/import_project.js, src/modules/utility.js
Remove debug console log messages before release 1.5.11.
=> Remove noisy logging messages before release.

src/modules/constants.js
=> Update to production release.

package-lock.json, package.json, src/modules/constants.js
Bump app version and build to next milestone.
=> Update file-save package to 2.0.5

src/modules/project/project_io.js
Board type was accidentally fixed to type "flip". Add code to parse the project board type from the project XML.
=> Retrieve the project board type from the raw project xml.

cypress/integration/page-load.spec.js, package-lock.json, package.json
Set up first end-to-end tests to verify that the toolbar buttons have been rendered. Testing these has identified an issue in the UI where the button elements are not completely rendered before the tests begin.
=> Add tests for buttons.

src/modules/editor.js
Adds balloon message to project board type icon when the mouse hovers over the icon for 500ms.
Addresses issue #639
=> Issue #639 - Add balloon message to project icon.

src/modules/constants.js, src/modules/dialogs/new_project.js
Addresses issue #638 by modifying the Edit Project -> Board Type drop down to list the current project board type and any other supported project board types.
Bump up build & release numbers.
=> Issue #638 - Refactor to limit board type conversion possibilities.

src/modules/editor.js, src/modules/modals.js
when project board type is changed in the Edit Project dialog, update the project board type icon to reflect the change.
=> Issue #638 - Update to change board type icon

.travis.yml, src/modules/dialogs/open_project.js
This update removes a message to indicate that the Open Project event handlers have already been installed. 
Updates the Travis CI configuration to use node.js 16.
=> Project hander message removed

README.md, package.json
Change URL for Travis-CI website.
=> Patch version update

.github/workflows/nodejs-ci.yml
Install node-pre-gyp package into the Ubuntu image.
=> Fixing node-pre-gyp build error.

.github/workflows/nodejs-ci.yml
Adding sudo magic to clear out npm cache.
=> Fixing node-pre-gyp build error - WIP

src/modules/blockly/generators/propc/communicate.js
Identified all alias references and prepared to replace aliases with actual code.
=> Preparing to move XBee blocks to separate module.

src/modules/constants.js
Release 1.6.1.
Details provided in the release notes on the main branch.
=> Release 1.6.1

webpack/prod.config.js
Streamlining the webpack configuration.
=> Remove unused configuration.

src/modules/editor.js, src/modules/project.js, src/modules/project/project_io.js
Complete the version 1 project file format. This version adds two fields to the file:
* version - this is the project file layout version number. It will be needed to help guide the code base through the changes in project blocks that will occur as the project moves through the newer versions of Blockly core.
* uuid - this is a unique hash ID for the project file.
=> Finalize a version 1 project file format.

src/modules/blockly/generators/propc/sd_card.js
Minor updates to the SD card blocks.
=> minor refactoring. Remove unused @types.

package-lock.json, package.json
Changed the location for the root SCSS source file. Updating the package.json file to reflect that change,.
=> Update SASS source file

src/templates/index.html
Correct errors in image path declarations.
=> Correct image path for OS icons.

src/modules/blockly/language/en/messages.js, src/modules/editor.js
Work continues to refactor code that references the jQuery library to remove those references.
=> 1.7 no jquery

src/modules/constants.js, src/modules/editor.js, webpack/prod.config.js
The original code was expecting a single matching element to which it would attach an EventHandler object. The 'show-os-???' class appears in at least two elements in the index.html page. The original code used  jQuery to handle this. The latest jQuery refactor introduced this error.
This update refactors the code to identify and attach an event handler to every element that is using the specified class.
=> 739_Refactor to address an array of elements.

package.json, src/modules/blockly/language/en/messages.js
The GitHub build action is failing because the .css bundle is not where webpack expects to find it.
=> Output css bundle where webpack expects to find it.

README.md, src/modules/editor.js
Remove the old jQuery code that was replaced with traditional Javascript.
=> Clean up dead code in editor.js

src/modules/constants.js
=> Update build number for production release of 1.7.0
