- blocklyc.html
- index.html
Addresses #5 
Must be used with CDN changes in the 1.3 branch
- Makes HTML valid in editor (blocklyc.html)
- Moves new project and edit project details a modal in the editor
- does this by adding a modal in the editor and adding the appropriate UI and project controls into the editor.js file in the CDN
- Markdown editing is NOT present for the details field (the markdown editor does not work inside of a bootstrap modal, which is an issue with the simpleMDE dependency).
- probably not worth fixing.
- blocklyc.html is _auto-generated_ from blocklyc.jsp
Unit tests should include
> Refactor html pages for open new project

- blocklyc.html
Reference issue #7 
This update adds an access attribute to the input tag  used in the open file dialog. The access attribute filters for .svg files with this construct:
```
accept="image/svg+xml" 
```
The result is a dialog that lists all on the files in a target directory, but only the .svg files are available to be selected. All other file types are greyed out.
> Issue 7 add filter project open load dialogs

- blocklyc.html
Reference Issue #9 
The href for the anchor tag associated with the logo in the upper left corner of the project editor page was empty. This update changes the empty URI to 'index.html', the project home page.
Although not required, it might be a good idea to change this in the future to an onClick event so the app has a chance to evaluate the project state - i.e. unsaved changes - before returning to the home page.
This update also correct the application name displayed on the page header.
> Correct href to point to the home page. Update the app name.

- blocklyc.html
Removes "Download blocks file" option in editor menu by making it an online-only option.  Because saving a project in the offline application is the same ad downloading it, the option is redundant and unnecessary.
A corresponding change will be made to blocklyc.jsp to keep it aligned with this project.
> Solo 16 remove download option from menu

- page_footer.html
Addresses issue #22.
Remove extra '/' in the URL.
> Correct broken license link

- blocklyc.html
Addresses Solo Issue parallaxinc/solo#26. 
The static HTML pages expected to have static help HTML files available in the ~/cdn/help directory. However, this directory was not published within the CDN.  This update replaces the reference to the static files with a link to the help pages available on the Parallax Learn site.
> Issue 26 block help links yield 500 error

- blocklyc.html
- inc_logo.html
- inc_logo_local.html
- inc_logo_solo.html
**This code must be used in conjunction with [BlocklyProp-cdn PR # 159](https://github.com/parallaxinc/BlocklyProp-cdn/pull/159)!**
Removes tables, replaces them with plain <div> tags carefully arranged.  Opted not to use grid or flexbox as both were overly complex for the editor's layout.  If we begin targeting mobile devices with narrow screen resolutions, we may need to revisit the layout, but for computers and tablets, it should work well.
Because so may changes were made to the structure of the div's in the navigation header, I opted to use a code beautifier to realign and double-check the tabbing and open/close tags.
Unfortunately, the beautifier causes the file diff to be nearly useless, so if there are specific questions about what changed, I'm happy to review them.  Primarily, it …
> Refactor and beautify HTML to remove tables

- blocklyc.html
- inc_logo.html
- inc_splash.html
- index.html
- page_footer.html
Addresses new issues in #35 - Update editor page layout.
Restore the background image in the upper left corner of the home page.
Applies brute-force branding for Solo until a better branding method can be developed.
Restores filter in Open Project dialog to allow selection of only svg files.
> Issue 35 editor page update breakages

- blocklyc.html
- index.html
The browser tab displays "BlocklyProp Local". This patch changes the default to "BlocklyProp Solo" until a better solution appears.
> Hard-code the page title. This is a temporary patch.

- blocklyc.html
Turns off the "inDemo" fuse, which will disable prop c editing and any blocks or features tagged "experimental".
Addresses #34
> Solo 34 disable prop c editor

- index.html
- page_footer.html
This addresses parallaxinc/solo#41.
The current license link connects the user to the license page on the blockly.parallax.com site. The then requires the user to know that they must select the 'Back' button in order to return to the Solo site. 
This update places the license text in a modal dialog window, where the user can read and then dismiss the license text.
> Add modal window to display license.

- blocklyc.html
Addresses issue #48 
Replace the target URL in the HTML code to point to the online help available at the Learn site.
> Correct URL for hamburger-help option

- blocklyc.html
Add an element id to the online help anchor element to allow JavaScript code to dynamically change the URL. This is an update to the code @MatzElectronics provided in that the default URL is now valid and the JavaScript code is now searching for the element id instead of the default URI.
> Issue 48 hamberger help

- blocklyc.html
Correct missing html label element 'for=' to reference the use the correct associated input element.
Add inline documentation.
> Correct label for element designations.

- blocklyc.html
Remove elements in the HTML that relate to displaying user authentication state. They are not applicable to this project. This is related to a pending update in the CDN repository that updates code to manipulate these UI elements only in the BlocklyProp UI. 
Also reformatted HTML elements to help make the functionality of each block more obvious.
> Remove user auth UI elements

- src/editor.js
- src/modals.js
Addresses issue #92.
Re-enable code to display the number of minutes since the last save.
Add a global constant to set the default time to wait before prompting the user to save their project.
Move Save Project timer code to a common section in the file.
Move the ShowProjectTimerModalDialog function to the modal.js file.
> Correct missing time in Save Project message

- blocklyc.html
- src/editor.js
- src/modals.js
Addresses issue #99 
The new project modal dialog contains a \<form\> element. When the user is in the project name field and presses the Enter key, the form returns without triggering the modal event handlers for the buttons on the modal and the onClose event for the modal itself. The net effect is that the modal closes and appears to do nothing. 
This update traps the Enter key when the modal is active. It verifies that the key did not come from a form \<textarea\> element (we want the enter key to work there) and then treats the Enter key event the same as if the user had clicked on the default Continue' button.
> Addresses issue #99.

- src/blockly/generators/propc/variables.js
Addresses #103 
Simplifies onchanges handlers that populate the dropdown menus where users choose the array variable name from the array blocks.
The previous implementation was searching for and calling functions within the init blocks, leading to a large cascade of events.  This fix should enhance performance and reduce errors.
To test
- Set up at least 2 array init blocks with different names
- add at least 1 of each of the other types of array blocks.  Ensure you can select between the available array variable names.
- change one of the names in one of the array init blocks, make sure the changes are mirroring on other array blocks using that variable name
- save and reload, ensure that all blocks re-render correctly.
> refactor onchange handlers for array blocks

- blocklyc.html
- src/style-editor.css
Addresses #119 
Corrects a few small styling issues to improve readability in the top nav bar and on block dropdowns:
To test:
1.) hover over each button to make sure it is readable in it's highlighted state
2.) choose any block that has a dropdown menu.  When the dropdown is selected, there should not be a vertical scrollbar (caused by the max-height property being too small)
> Remove duplicate styling, make buttons readable on hover

- blocklyc.html
- package-lock.json
- package.json
- src/editor.js
- src/modals.js
- src/style-editor.css
This is an update to PR #120 to correct merge conflicts.
Makes the project name editable, and after editing, updates the projectData object with the new name.
Setting a default name, etc. can (and should be) be dealt with in issue #115.
To Test:
1.) click the project name in the top-right corner
2.) Make sure the styling changes (blue outline)
3.) edit/change the project name
4.) when you click elsewhere (de-focus the project name), the styling should return to normal.
5.) Choose "edit project details" in the hamburger menu to make sure the new project name persists.
> Make project name editable - Deconflicted

- blocklyc.html
- src/blocklyc.js
- src/deprecated/project.js
- src/deprecated/shared-editor-demo.js
- src/deprecated/shared-editor.js
- src/editor.js
- src/modals.js
- src/style-editor.css
Makes the project name editable, and after editing, updates the projectData object with the new name.
Setting a default name, etc. can (and should be) be dealt with in issue #115.
To Test:
1.) click the project name in the top-right corner
2.) Make sure the styling changes (blue outline)
3.) edit/change the project name
4.) when you click elsewhere (de-focus the project name), the styling should return to normal.
5.) Choose "edit project details" in the hamburger menu to make sure the new project name persists.
> Make project name editable

- src/editor.js
- src/style-editor.css
Update the CSS to tone down the border surrounding the project name on the edit page when the user is editing the project name.
Added tasks to remove the concept of project owner. In Solo, the project owner is the individual who possess the project file. In BlocklyProp, project ownership is determined when the project is created and stored in the cloud infrastructure.
> Issue 106 supplemental update

- src/editor.js
Addresses last remaining issue in #106 where a user can type in a very long project name, and after leaving the field, the beginning of the project name was truncated.  Fixed by forcing the cursor back to beginning of the text right before the field is blurred (focus removed)
> Move cursor back to beginning of text on blur

- src/modals.js
Address issue #146.
The bootstrap modal dialog as implemented in Solo responds to the button clicks and to the event fired when the Enter key is pressed. There is also an anti-pattern when the 'X' button that dismisses the modal windows is clicked. This does not fire a 'click' event, but instead fires a 'hidden.bs.modal' event when the modal is closed as a result of the click detected on the 'X' icon in the modal.
The PR adds code to detect the hidden.bs.modal event and attempts to reconstruct the existing project if there is one. Otherwise, it returns the user to the home page to start a new project or to load an existing project.
> Modal dismissed with 'x' click invalidates editor canvas

- src/blocklyc.js
- src/editor.js
Addresses #133 
The keybindings were an attempt to address an issue where both the ace editor (for propc code) and blockly were both initialized, and both were reacting to cut, copy, and paste (ctrl-c/ctrl-v/ctrl-x) keystrokes.
Since code-editing is not fully supported, these can be deleted without issue.
Ultimately, when we are ready to work on supporting using BlocklyProp as a prop-c editor, then the better solution would be to only initialize the ace editor and not initialize blockly at all in prop-c mode.  Such improvements are best addressed as part of #110, since both are related.
> Solo 133 Remove deprecated keybinding calls

- index.html
- src/editor.js
- src/utils.js
Addresses issue #183 
The latest Blockly core uses a different XML namespace than previous versions. When project files created with older versions of the core are loaded, the XML namespace declaration in the projectData variable will not match the XML namespace provided from the call to getXML(). This causes the system to identify the current project as having been modified when, in fact, it has not.
This patch skirts the issue by locating the beginning of the actual project code and then begin the comparison from that point.
This patch also removes four redundant lines of code that were erroneously  inserted in a previous PR.
> Issue 183 project change detection

- src/blockly/generators/propc/base.js
Addresses recent discussion from #111 
Does not address broader issues with the constant define blocks.  My opinion is that the remainder of the issues should be addressed as part of #175. 
To test:
- Create a string var length block and mutate it to include a named constant.  The block should throw a warning.
- To test code generation you'll have to assign a string to the item variable, but then check to see that the MYVALUE constant is defined to 64 (default value for string length).
- Drag another string var length block out, check to see that the warning now contains warnings about both the extra block and undefined constant.
- Delete the extra block, define MYVALUE, ensure the warning disappears.
> Solo 111b Generate code for MYVALUE if not already defined

- src/blockly/generators/propc/communicate.js
Addresses #195 
Dropdown change handler was missing an argument and behaving badly because it now gets fired when blocks are dragged out of the toolbox.
This provides a value in the change handler and uses that value in the domToMutation for the block.  This also separates the two mutations - before, if one type of mutation was set, reloading the block would load them both.  Now only the set mutations are loaded.
To test: drag out Communicate > Protocols > Serial Initialize from the toolbox.  If it doesn't freeze up and generates working code, the bug is fixed.
> Solo 195 Fix dropdown change handler

- src/blocklypropclient.js
- src/editor.js
Addresses issue #203 
This is not needed with the new BP Launcher. Updated code comments to document what the code is doing with the UI.
> Marked the configure_client function as deprecated.

- src/editor.js
- src/propterm.js
Create a Terminal Options class to support the 'options' in the Propterm class.
Refactor code in Propterm that referenced generic options object to use TerminalOptions class.
> Updates to Propterm class

- .eslintignore
- src/blockly/generators/propcToolbox.js
- src/editor.js
Correct a number of warnings where variables were used before being declared in filterToolBox().
initToolBox() Does not have two parameters. Removed the second parameter, an empty array. 
Added type declarations to clean up variable type warnings.
.eslintignore should be ignore src/lib*, not /src/lib/*
> Clean up lint warnings

- src/propterm.js
* _getCharacterSize() contained code that was referencing getCharacterSize(), which does not exist. I am guessing that the private underscore notation was added after the function was created and tested.
* CamelCase keyCode to quiet the spell checker.
* Add todo tasks for remaining unresolved elements and attributes.
* new Array is ES5, [] is ES6. 
* Remove unnecessary code and added missing statement termination.
> Correct eslint warnings

- src/modals.js
Updated the wording in the dialog that opens after clicking on the Open button and the current project has unsaved changes to indicate that an existing project will be opened and that it will not create a new project.
> Update Open Project Save Current Project dialog box message

- src/propterm.js
Address a lint error in the Propterm class where a numeric parameter is passed into the _updateTermBox() method and code in that method was attempting to treat the parameter as a string and converting it onto an number.
> Lint error - variable is a string and/or a number.

- src/editor.js
- src/project.js
Correct an issue where compareProjectCode() was accessing the parameters without validating that they actually contained data.
Refactor the EmptyProjectCodeHeader constant defined in the Project class to become a property of that class. This will enable the global replacement of the EMPTY_PROJECT_CODE_HEADER constant, which is only referenced within the context of project code.
Add console messages to the project comparison function to help identify edge cases when the projects differ.
> Updates to add parameter testing

- src/editor.js
- src/modals.js
The vertical scrollbar on the editor canvas was not rendering for large projects. Further testing against the 1.3.512 build was unable to reproduce the issue. However, a new issue was discovered where loading a new project would result in the previous project, if there was one, would be loaded onto the editor canvas.
The root cause was that the code responsible for loading a project from the localStorage was not clearing the localStorage after the project was loaded. All other components expect the localStorage to be clear (empty) if there is no successor to the currently loaded project.
> Correct editor vertical scrollbar issue

- src/blockly/generators/propc/communicate.js
Addresses #231 
Basically was just a copy-paste error when updating variable names in the PR that broke this.
> Fix missing array variable

- src/blockly/generators/propc/communicate.js
Addresses #195, again.
The learning here is that blockly is creating a hidden copy of the block (for sizing/insertion/etc), when you drag a block - and if the new block does not generate the same fields as the existing block has (via the `mutationToDom()` function), it breaks the workspace badly.
> Solo 195b fix serial init block part2

- src/modals.js
Found two errors in the modal.js file related to loading a project with an experimental query string component. The first was not detecting a null project and forcing the redirect. The second issue was the Open Project feature was truncating the experimental query string after successfully loading the target project.
> Correct error in query sting processing in issue #167

- src/blockly/generators/propc/sensors.js
Addresses #242 
Extra semicolon is causing an issue with the generated code.  This PR removes it.
> Remove semicolon that is clobbering code generation

- blocklyc.html
- index.html
Addresses issue #252 
Update links to new generic latest version launcher files to new location in S3. This also realigns the release cycle directory tree such that the latest release is always in the /blockly/launcher folder and specific release numbers are in their respective sub folders. For example, release 0.11.0 is now located in the /blockly/launcher/0.11.0/ folder.
Bump version number of next milestone.
> Update Launcher client URLs

- src/blockly/generators/propc/communicate.js
This patch corrects two errors relative to issue #246
* Eliminates errors when a project containing a serial init block is dragged on the canvas. The Blockly.FieldDropdown object requires an array argument. Identified and corrected two uses of this object that were passing in an object containing an array instead of an array. 
* Corrects error where the serial block variable name was truncating the second pin name. 
Array.isArray was breaking ser_pin settings.
* Add more inline documentation.
> Address additional defects in serial blocks

- blocklyc.html
- src/blockly/language/en/messages.js
This PR addresses issue #247.
It reworks the message as specified and corrects an issue where the 'Older Clients' button was mis-aligned below the 'OS-Selector' drop down element
> Update BP Launcher upgrade message

- src/editor.js
This corrects the issue where the user renames a project file outside of the application and expects the new filename to become the project name. The code discards the project name metadata element and replaces it with the actual filename without the file extension.
> Refactor uploadHandler to use the filename as the project name.

- src/blockly/generators/propc/variables.js
Code generation (`Blockly.propc.valueToCode`) should not be used inside of a block definition.  It was being used to see if the connected block contained a number value.  This replaces that code with code that looks for the **math_number** block and if found, it's field value.
> Solo 263 fix type error in array block

- src/editor.js
Addresses issue #273. 
The project checksum and the computed checksum are no longer matching after the last Blockly core update. An error in the code that displays an error message was effectively masking this issue when a new project was loaded. This same code works correctly when importing a project to an currently loaded project and was blocking all imports due to the checksum error.
The checksum feature was designed for the BlocklyProp system and is no longer applicable in the Solo system. This update removes all of the checksum computations. Projects are now persisted to storage with a default all zeros checksum to allow legacy loader code to still see the checksum object. This also effectively removes any data validation during the project load sequence and relies on downstream code …
> Deprecate project file checksum.

- blocklyc.html
- index.html
- package-lock.json
- package.json
- src/globals.js
- src/index.js
This patch implements a basic implementation of the Sentry remote error logging system identified in issue #298.
Sentry attaches to the root error handler and waits for any errors to be trapped by the root error handler. When an event does occur, the detail surrounding the error are sent to a logging server for analysis and possible triage.
> Implement remote error logging.

- index.html
- src/blockly/generators/propc/sensors.js
Addresses continuing issues wth #311 
This update addresses an error discovered in testing the new ADC calibration code. The adc_init() must be called with four zero parameters during calibration. After the user has provided the ground and 3.3.V adjustments, the first two parameters in adc_init() must be set to 0, 3300. The remaining two parameters are the user supplied ground and 3.3V settings.
> Patch develop 311

- src/blocklyc.js
- src/blocklypropclient.js
Adds a client connection URL generating function to the `clientService` object.
Cleans up some dead/unused code
To Test:
Make sure solo is able to connect to both the BPC and BPL, including:
- showing connection
- enumerating ports
- facilitating serial/console/terminal comms
- load programs to propeller devices
> Solo 200 resubmit E client URL formatting function

- src/blocklyc.js
- src/blocklypropclient.js
Remove dead code
Add inline comments
> Inline documentation update

- src/blocklypropclient.js
- src/editor.js
The launcher was not encoding one direction of its serial comms stream.  There is a PR in the lanucher's repo holding on this change:
[BlocklyPropLanucher-96](https://github.com/parallaxinc/BlocklyPropLauncher/pull/96)
This adds code to compensate for that issue across all versions of the launcher.
> Solo 200 resubmit G - Handle differences in encoding between launcher versions

- src/blocklyc.js
- src/blocklypropclient.js
- src/editor.js
Pull after #337 
- Renames more functions and variables to bring them inline with style guides
- Moves flags used by the launcher for loading binaries and logging into the `clientService` object, eliminating them as globals
- Answers/clarifies questions posed in code comments
> Solo 200 resubmit H - More variable and function name updates

- src/blocklyc.js
- src/blocklypropclient.js
- src/editor.js
Major simplification of the heartbeat functions.  Previously, heartbeat functions were tangled, and called redundantly, and separated for the BPC and BPL.  This PR combines them into a single `setInterval` the fires every 3.5 seconds.
Additional variable name replacements were made to support the heartbeat simplification, namely the active connection object.
> Solo 200 resubmit I - simplify heartbeat and move connection objects

- src/blockly/generators/propc/gpio.js
Addresses #339 
To reproduce error:
- build the following program:
- select "waveform" first, then try changing that same menu to a different option - that should reproduce it.
This PR corrects the bug by checking for the connection before trying to access/delete it.
To test:
- same steps as above, make sure no error is generated.
> solo 339 - Check for connection before deleting it

- src/blocklyc.js
- src/editor.js
Final PR to address #279.
Last few global variables that are now either replaced with variables inside of the clientService object, or placed inside of the sole functions that use them.
> Solo 200 resubmit K replace connection globals with object variables

- src/blockly/generators/propc/variables.js
Addresses #251 
Array blocks were not maintaining their menu values because the menus were not being populated immediately after the blocks were built, effecively resetting them to their default values.
Tested with the original large pixycam project provided by @kgracey
> Solo 251 - Fix array name menu population

- src/editor.js
Addresses #357 
Uses an XML parser for extracting the project content (stripping off the XML tag).
Also generalizes the `variables` tag finder, as some of them appear to have attributes, which would have broken the import of additional blocks files if that wasn't changed.
There is still work to be done on at least the upload side of the SVG file builders/parsers to make them more robust and less dependent on fixed length strings that could change.
To test
- open, save, reopen a few files
- open a file containing variables, and import a different project with variables, then save and reopen
- make sure there are no console errors.
> Solo 357 Fix SVG creation function

- src/editor.js
The compile toolbar shows the load-to-ram button as active when an S3 project is loaded on a Chromebook an the Launcher/Client is not enabled.
> Correct compile toolbar defaults

- src/blocklypropclient.js
- src/editor.js
Replaced setPropToolbarButtons function with PropToolbarButtonController.
Refactored old function to remove the reference to the clientService class.
Add code in the editor.js to properly set the button state when loading a project without regard to the client connection state.
> Correct Load to RAM button for S3 projects

- .eslintignore
- .eslintrc.yml
- index.html
- package-lock.json
- package.json
- src/blockly/generators/propc/communicate.js
- src/editor.js
- src/globals.js
- src/index.js
- src/modules/constants.js
- src/modules/index.js
This update refactors the entire home page to use ES6 modules. The src/modules directory contains all JavaScript modules used in the project.
The ESLint configuration has been updated to continue linting all ./src file except those in the ./src/modules tree. There is a special override in the configuration to treat all .js files under the ./src/modules tree as JavsScript modules. Furthermore, the linter is now using the somewhat more stringent [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html). There will be a transition period where most of the issues raised will be converted to warnings.
> Begin migration to ES6 modules

- src/blockly/generators/propc/communicate.js
- src/blockly/generators/propcToolbox.js
Refactors the functions that handle the RXTX (pin selection) dropdown in the serial protocol blocks.
- Transitions the mechanism from using "sending" functions in the serial intialize blocks to monitoring `onchange` events for pin menu changes in the init block.
- Collapses the functions handling menu building and change monitoring were collapsed and generalized, allowing them to be copied into all other blocks.
- Uses a new method (`array.filter`) to find the difference between past and updated states, allowing for more efficient monitoring of menu changes that apply to the block in question.
- Tests for existence of field test before setting its value (may want to apply this elsewhere down the road)
To test:
- Create a project using a *serial init* block and each of the other serial …
> Solo 365 - Fix RXTX dropdown on serial protocol blocks

- src/README.md
- src/blockly/generators/field_ace.js
- src/blockly/generators/propc.js
- src/blockly/generators/propc/communicate.js
- src/blockly/generators/propc/gpio.js
- src/blockly/generators/propc/heb.js
- src/blockly/generators/propc/sensors.js
- src/modules/blocklyc.js
- src/modules/code_editor.js
- src/modules/editor.js
- src/modules/project.js
- src/modules/project_profile.js
Refactor code to remove projectData references.
Refactor code to remove global codePropC references.
Update src/README to include more updated blocks.
The UI is again able to view the C source code generated from the project blocks.
> More refactoring to eliminate globals

- src/editor.js
Address Solo #405
A project containing one or more older version blocks is converted to the current version of the block. This change will trigger the project comparison code to identify the change. Also added log messages to help understand when projects changes.
> Project can change immediately after loading 

- index.html
- package-lock.json
- package.json
- src/modules/blockly/generators/propc.js
- src/modules/blockly/generators/propc/variables.js
- src/modules/blocklyc.js
- src/modules/code_editor.js
- src/modules/editor.js
- src/modules/index.js
- src/modules/project.js
- src/modules/toolbar_controller.js
- src/modules/utility.js
- webpack.config.js
* Correct import of the utils object. The bits from the original ./src/util.js file were moved to ./src/modules/utility.js.
* Remove script tags that loaded jquery and bootstrap in the index.HTML file. The jQuery package is now loaded as a global import in the webpack configuration file. Bootstrap is now loaded through an import statement as needed in each module.
* Remove debugging log messages.
* Add chunking support to webpack config.
* Clean up unneeded regEx escape characters.
* Refactor calls to cCodeEditor find and replace methods with methods exposed in the CodeEditor object.
* Update fsevents package to remove CVE. This is a dev package and only relevant to development under MacOS.
> Patch fm 200413a

- webpack.config.js
Docker images were not receiving the .css files from the source repository. Update the webpack config to copy these assets to the /dist folder as part of the webpack build process.
> Add block to copy CSS assets to /dist.

- src/modules/blockly/generators/propc/base.js
- src/modules/constants.js
Addresses issue #434 
The 'color_value_from' block code generator was returning a string representing a function call and not the RRGGBB hex value string the receiving block was expecting. The NaN was generated when the block tried to parse the string function as a hex value and failed. 
This update also bumps up the release to v1.5.0-b3.
> Issue #434 - Block generating NaN

- package.json
- src/modules/blockly/generators/propc/base.js
- src/modules/blockly/generators/propc/oled.js
- src/modules/constants.js
- src/style.css
Correct an error in the color_value_from block that caused it to generate incorrect RRGGBB values from the provided inputs.
Add line feeds to sections of the code generator to help eliminate run-on source lines.
Address a browser warning triggered from the CSS defined in the ace package.
> Release v1.5.0-b5

- package-lock.json
- package.json
- src/modules/dialogs/import_project.js
- src/modules/dialogs/open_project.js
- src/modules/editor.js
- src/modules/project.js
Large refactor of import_project module to fully manage the import dialog and import project process.
Updates to disable project load and import buttons when a project file has not been selected.
Rename uploadMergeCode(append) to appendProjectCode() because merging code is all it really does.
Correct error in Project class constructor that was replacing the default project with the one being instantiated in the constructor.
Update websockets-extension package to correct a security issue.
> Patch fm 200609a

- src/modules/blockly/generators/propc/variables.js
Addresses issue #447 and #251 
The array_fill.buildArrayMenu method was reacting poorly to a truncated internal list of array variables where the array variable assigned to the current array_list block was no longer in the list. This would cause the block to render as array variable assignment that just happened to be the first item in the internal array list.
This update provides a work-around to the error while work continues on the root cause.
> The internal array list was incomplete when building new input field.

- src/modules/toolbox_data.js
Addresses issue #473 
The toolbox menu for Memory-> SD Cards does not contain the SD_Init block for the Flip board type. This patch corrects the issue by adding the missing block to the toolbox Memory-SD Cards menu.
> Solo-473 - Add SD_init block to the toolbox menu for Flip board type.

- package.json
- src/modules/blocklyc.js
Addresses Solo #484  - Verify non-null activeConnection before accessing it.
Reorder npm run scripts.
> Patch for issue 484 

- src/modules/editor.js
Addresses issue Solo #485 
It appears that there is no method within the Blockly core at v2019.722x that supports rebuilding the entire toolbox. The alternative implemented here is to remove the HTML created from the Blockly.Inject call and rebuild the canvas and toolbox with a new call to Blockly.Inject.
> Solo-485 - Rebuild Blocky div on toolbar change.

- src/modules/blockly/language/en/messages.js
Resolves issue Solo #488 
This update simply removes the overridden showHelp_() method and relies on the showHelp() method in the Blockly core.
> Solo-488 - Remove override of Blockly private method.

- src/modules/blockly/generators/propc/gpio.js
- src/modules/blockly/generators/propc/sensors.js
Addresses Solo #490 
This error is caused by a failed attempt to access a member of the profile.analog array. This can only happen if the array is empty. There is insufficient data to reach a conclusion on the exact cause. The analog array could have been truncated or the board type is set to a board that has an empty profile.analog array.
To address the uncertainty, Sentry messages are added to the reported methods to help us determine the board type and the state of the profile.analog array when this condition occurs.
> Patch for Solo-490 issue

- package.json
- src/modules/blockly/generators/propc/s3.js
- src/modules/constants.js
Addresses issue #493 
The C code generator was swapping two of the three outputs and creating code that would not compile. Refactored the method to generate the correct output.
Update version to 1.5.2 in the development branch.
> Update version and correct code generator output

- package.json
- src/modules/blockly/generators/propc/aliaes.js
- src/modules/constants.js
Release Solo v1.5.4
Add in two block aliases that were inadvertently omitted in the last release.
> Address solo issue #507.

- webpack/dev.config.js
- webpack/prod.config.js
Update the CopyPlugin configuration in the dev and prod Webpack configuration files to correct build errors related to the plugin configuration.
> Webpack CopyPlugin now expects an initializer object.

- src/modules/blockly/generators/propc/communicate.js
Removed an extraneous regex that was converting a single '%' to a double '%'. Refactor the affected block to lift redundant code from the if/else statement.
Addresses issue #521
> Solo-521. Remove regex expression. Refactor code block.

- src/modules/blockly/generators/propc/gpio.js
Refactor the SD_Read block. Correctly detects that required blocks are present and **enabled** 
Replaces simple file close with file close only if file is open.
Correct SD_read number input accepting string text.
Correct source code formatting - add line breaks.
Partially addresses Solo-#529
> Refactor sd_read code emitter.

- src/modules/blockly/generators/propc/gpio.js
SD card file handle is now a global.
Correct more cases where check for sd_init was ignoring the enabled state.
Correct missing line feeds in code emitters.
Refactor code that requested all project blocks to search for the sd_init block with code that just asks for the sd_init block.
Address issues raised in Solo-#529
> SD card block updates

- src/modules/blockly/generators/propc.js
- src/modules/blockly/generators/propc/sd_card.js
- src/modules/blockly/language/en/messages.js
- src/modules/constants.js
- src/modules/toolbox_data.js
This request includes two updates, a new sd card reader block and a deprecated block warning system.
**SD File Close Block**
Added a new block to specifically close an open sd card reader file. Prior this this, opening a second file in the project orphaned the file handle from the previous file open.
**Deprecated Block Warning**
Added visual indicators to a block that has been slated for deprecation. These cues include a change in the block color, a triangle warning on the block face and a notice comment embedded in the generated source code. All of these indicators should make it clear that the project should be updated with either a new block or rework the block code to eliminate the deprecated block.
> Add sd_close block and implement deprecated block warnings

- src/modules/blocklyc.js
This corrects the issue where a terminal window was opened for a project that contained terminal-dependent blocks and all of those blocks were disabled. The previous behavior would open a terminal window and just sit there.
> Refactor code that looks for active terminal-dependent project blocks.

- README.md
- src/modules/editor.js
This addresses issue #557 
Refactored the uploadHandler() function to catch the error thrown when an older browser attempts to execute the blob.text() method and fails. 
Updated the project README to indicate minimum browsers versions support in this project.
> Refactor project loader to address unsupported browsers.

- src/modules/index.js
- src/modules/prop_term.js
Add code to detect browser name and version. This will be used later to warn a user that the browser they are using is not supported and will likely not work correctly with Solo.
Add code in the prop terminal module to help understand why the move_cursor is occasionally failing on an undefined .length property.
> Patch 1.5.7.2 a1

- .eslintrc.yml
- package-lock.json
- package.json
- src/modules/client_service.js
- src/modules/constants.js
- src/modules/editor.js
- src/modules/index.js
- src/modules/sentry.js
Refactor Sentry initialization as an async call to remove it from the mainline code path.  
Remove unused babble-eslint package.  
Update eslint to use version 8 and modules to correct an issue where the IDE was complaining about an unexpected token in async function construct.  
Remove unneeded console logging message.
> Patch 1.5.7.2 a3 sentry

- src/modules/blocklyc.js
- src/modules/compiler.js
- src/modules/editor.js
- src/modules/modals.js
* Refactor the cloudCompile() function into a new module.
* Split out the "empty project" alert to the modals module.
* Split out the terminalNeeded code to a separate function. This permits the callback to figure out the correct state of the terminalNeeded inside the callback. This also removes a dependency on the Project module from the cloudCompiler function.
> Compiler split

- src/modules/blocklyc.js
- src/modules/compiler.js
- src/modules/modals.js
* Functions that call cloudCompiler now must supply source code and open the compile modal window. This removes even mode dependencies the compiler module.
* Inverted logic in loadInto to handle bad data first.
* Moved UI code that inits and opens the compiler status dialog to the modals module.
> More compile module refactoring

- src/modules/blocklyc.js
- src/modules/client_connection.js
- src/modules/client_service.js
- src/modules/compiler.js
- src/modules/constants.js
- src/modules/editor.js
- src/modules/modals.js
- src/modules/utility.js
This update completes the changes necessary to gracefully handle the lost web socket connection that can happen while loading a program to a device.
* The app now is able to detect the connection failure and resubmit the download to the Launcher when the connection to the Launcher has been re-established.
* The UI port list dropdown is no longer automatically cleared when the web socket connection has been lost. Instead, it will retain the current list and only update the list when a new list is provided from the Launcher.
Addresses issue #514
> Updata 1.5.7.2 b1

- .eslintrc.yml
- src/modules/blocklyc.js
- src/modules/client_connection.js
- src/modules/client_service.js
- src/modules/compiler.js
- src/modules/constants.js
- webpack/dev.config.js
- webpack/prod.config.js
Complete refactoring of the code that sends compiled project payload to the Launcher. This update allows Solo to detect that there has been a web socket connection failure (see #394,  #514) and wait for the connection to be re-established before retrying the load operation. This effectively overcomes the issue in Chrome that is causing the disconnect.
Changed the port list behavior such that Solo will no longer invalidate the current port list if the web socket connection is lost. Instead, it will retain the list it last received from the Launcher until it receives an updated list from the Launcher. This improves the stability of the UI when the web socket connection is lost.
Removed a number of console messages that were no longer useful.
> Patch 1.5.8 b4

- src/modules/toolbar_controller.js
Addresses #572.
The toolbar controller has been relying on the first element of the port list to be non-blank to indicate a selected port. This update changes that to rely on the client_connection object as the single source of truth for connection state and queries the object for the current selected port.
> Rely on selected port to guide Load To button state.

- src/modules/blocklyc.js
- src/modules/client_connection.js
- src/modules/client_service.js
- src/modules/toolbar_controller.js
This update further addresses issue #572.  
Notify clientService when a com port is selected so it can notify the Launcher of the selection.
The setSelectedPort method now sends an update to the Launcher only when the selected com port has changed.
Migrate the hasCode function to the blockly module.
> Toolbar ghosting with valid connection - part 2

- blocklyc.html
- src/modules/editor.js
The BlocklyProp Client has been deprecated for over a year. The updates to Solo v1.5.8 are breaking changes for the Client. This update removes the UI elements that allow the user to download the BlocklyProp Client. Subsequent updates will begin removing the Client related code within the app.
> Remove all references to the deprecated BlocklyProp Client.

- src/modules/blockly/generators/propc/communicate.js
Located a console message in the serial_send block definition and removed it.
> Remove noisy console message

- src/modules/blockly/language/en/page_text_labels.js
Addresses issue #591. Update getHtmlText to always return a string, even when the key is not found.
> Correct getHtmlText not defined

- src/modules/client_connection.js
- src/modules/client_service.js
- src/modules/prop_term.js
Addresses issue #596
This corrects an error that assumed that the clientService.activeConnnection property was not null, as is the case when the connection is closed. 
This also contains a refactor of the findClient method that clearly separates the watchdog timing code from the code that is actually looking for a Launcher connection.
> Correct TypeError Cannot read property 'send' of null

- package-lock.json
- package.json
- src/modules/blockly/generators/propc.js
Replaces the July 2019 core with the November 2019 core. The new core has no breaking changes.
Updates to the propc.js file to remove functions that override core functions that were buggy. The new core has addresses those issues.
> Upgrade Blockly core from 2.20190722.1 to 3.20191014.4

- src/modules/blockly/generators/propc/sd_card.js
- src/modules/code_editor.js
- src/modules/constants.js
- src/modules/editor.js
- src/modules/index.js
Update the version tag emitted on the home page to include 'qa' and the build number for test builds that are targeted at SoloCup.
Correct issues identified by linter.
> Update version display

- package-lock.json
- package.json
- webpack/dev.config.js
Remove WebPack dev server. It is no longer used.
This eliminates a NPM package dependency for webpack-dev-middleware, which requires WebPack 4.x.
```
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
```
> Remove WebPack dev server

- src/modules/sentry.js
- webpack/dev.config.js
Change Sentry init to async implementation.
Update WebPack to split out vendor packages into a separate vendor bundle. Still working on tree-shaking.
> Patch sentry optimizations

- src/modules/blockly/generators/propc/control.js
Addresses issue #625.
Add a linefeed to the end of the "return;" statement.
> Add linefeed after the return statement.

- src/modules/editor.js
- src/modules/project/project_io.js
Rely on the project title metadata to name the project.
Add code to strip off the ".svg" and ".svge" extensions that Solo 1.5.11 added to the metadata.
> Pull project title from project file metadata.

- src/modules/blockly/generators/propc/procedures.js
- src/modules/constants.js
- src/modules/dialogs/new_project.js
- src/modules/modals.js
- src/modules/project.js
- src/modules/project/project_io.js
- src/templates/index.html
This update provides support to the Edit Project dialog to change the project board type. There are a number if things that can break if this is used indiscriminately. The primary purpose for this feature is to allow users to correct the project board type that were forced to the 'Flip" type due to an error introduced in release 1.5.11.
> Feature select project board type

- src/modules/constants.js
- src/modules/editor.js
- src/modules/project/project_io.js
This update removes the project ID and User fields that were a holdover from the original BlocklyProp project. These fields were populated with static data when a project file was created and were subsequently ignored when the project was loaded from storage.
> Deprecate and remove project fields

- .github/workflows/solo-develop.yml
- .gitignore
- src/scss/main.scss
- webpack/dev.config.js
- webpack/prod.config.js
I am unable to get webpack to compile scss files and place the results in the ./dist folder for production deployment.  The workaround is to use a webpack copy asset to copy the compiled .css file to the ./dist folder during production build.
> Updates to disable webpack handling of scss files.

- src/modules/client_connection.js
The HtmlElement object does not support a .modal() method. This method is specific to jQuery, sp a jQuery selector must be used when invoking the modal() method.
Addresses issue #661
> Replace plain Javascript with jQuery that supports .modal() method.

- package.json
Update the Sentry packages to version 6.10.0.
Addresses issues #660 and #662.
> Correct path in SASS compile script. (more)

- src/modules/constants.js
Release 1.6.0-update-1 to correct  a TypeError when the Launcher sends a message to the client to close the Cloud Compiler dialog window.
> Bump the build number. Release patch for compiler dialog fault.

- src/modules/constants.js
- src/modules/editor.js
This update addresses issue #668 by changing the parameters passed in the new Project() constructor from text date strings to Date objects.
> Issue 668 - Cannot create new projects

- src/modules/blockly/generators/propc/sensors/sensors_common.js
- src/modules/blockly/generators/propc/sensors/sound_impact.js
This update provides more fine-grained handling of constant values in the pin list. When a constant block is deleted, we now check to see if this constant is the currently assigned pin. If it is, we complain to the console and set the pin value to the first element of the pin list. Otherwise, the deleted constant is removed from the pin list.
When a constant block is created or restored from the trash can, we now add that constant to the pin list.
> Patch more constants

- src/modules/blockly/generators/propc/gpio.js
- src/modules/constants.js
The ab_drive_block appears in two places in the global toolbox menu. one was marked as experimental and was subsequently removed. The ab_drive_speed block was also removed from the deployment. This update replaces the block.
> Hot-fix 1.6.1.1 to install the ab_drive_speed block.

- src/modules/blockly/generators/propc/gpio.js
- src/modules/constants.js
This hotfix reinstates the omitted ab_drive_speed block.
Release 1.6.1.229
> Hotfix - missing ab_drive_speed block

- src/modules/blockly/generators/propc/propc_common.js
- src/modules/blockly/generators/propc/sensors/sound_impact.js
BuildConstantsList() now ignores disabled constant blocks. This has the effect of removing the disabled constant from the refreshed pin list.
Correct error where a disabled block does not have an event.name. A change event is triggered when any block is disabled. The event object that is passed into the change handler does not have a 'name' property, so name of the block that was disabled is not readily discernible. The change handler now verifies that the name property is available before using it.
> Update change management for references to constant blocks

- package-lock.json
- package.json
- src/modules/constants.js
- src/modules/editor.js
This is the last release of the '3' series Blockly Core. It get way more interesting from here.
Enable Sentry.
> Update Blockly Core to v3.20200924.4

- src/modules/blockly/generators/propc/sd_card.js
- src/modules/toolbox_data.js
This block attempts to open the target file in read-only mode. If the open fails, the block returns a zero value. Otherwise, it returns a non-zero value. 
The code emitter for this block creates an embedded function int file_exists(). 
Addresses issue #540
> Created SD File Exists block.

- src/modules/blockly/generators/propc/sd_card.js
- src/modules/blockly/generators/propc/sensors/temp_dht22.js
- src/modules/editor.js
A callback function was attempting to perform string manipulations on a string variable that was empty. Added code to verify that there is text in the filename variable before performing string manipulations on the variable.
Cleaned up a few lint errors that were not detected during the last build process.
> Correct TypeError on SD block filename variable

- src/modules/blockly/generators/propc.js
- src/modules/blockly/generators/propc/sd_card.js
- src/modules/blockly/generators/propc/variables.js
When the  file_exist() function is assigned to a variable, the return type of the function must be declared in the emitted code. Failure to do so causes the emitter code builder in propc.js to declare the variable as type 'float'.
```
// Check for the file we just wrote
item = (int) file_exists("filename.txt");;
print("Hello");
```
There are some odd things happening in propc.js around line 274 where the code is parsing definitions and assigning variable types. Without the ``` (int)``` type declaration in the emitted code, the parser declares the function as a float because it finds a decimal point in the first argument,  ```argument0 = "file_exists(\"filename.txt\");"```. With the int cast, the code searches for an int declaration when the function is used and subsequently types the …
> Patch SD file exist

- src/modules/blockly/generators/propc/communicate.js
Correct a typo in the inline docs.
> Correct document typo.

- src/modules/blockly/generators/propc/sd_card.js
- src/modules/constants.js
- src/modules/editor.js
Interim release to address an issue where Chrome no longer permits secured pages to link to insecure URLs. 
Addresses issue #703
> Release 1.6.3

- package-lock.json
- src/modules/blockly/generators/propc/variables.js
- src/modules/constants.js
Adds popup comments to the variable blocks to help identification of the blocks when used on the workspace. 
Removed unused field references.
> Add comment elements to variable blocks

- package.json
- src/modules/blockly/language/en/page_text_labels.js
- src/modules/constants.js
- src/modules/editor.js
- src/templates/index.html
The previous version of the launcher was failing when installed in a Mac running macOS Ventura. The launcher package was updated and released as version [1.0.7](https://github.com/parallaxinc/BlocklyPropLauncher/pull/131).
The Mac operating system text references were changed from MacOS to macOS.
> Add updates to support new launcher release for macOS Ventura.

- src/modules/blockly/language/en/page_text_labels.js
- src/modules/constants.js
Correct text in the BP Launcher dropdown dialog for Windows to include Windows 11 and remove Window 7, which is no longer supported by Microsoft.
> Correct text to include Windows 11 and remove Windows 7.
